NXU_TARGET ?= aarch64-unknown-none-softfloat
NXU_MANIFEST := nxu/Cargo.toml
NXU_ARCHIVE := nxu/target/$(NXU_TARGET)/release/libwindowserver_nxu.a

.PHONY: nxu

nxu:
	cargo build --manifest-path $(NXU_MANIFEST) --release --target $(NXU_TARGET)
	mkdir -p build
	cp $(NXU_ARCHIVE) build/libWindowServer.a
	cp include/WindowServerNXU.h build/WindowServerNXU.h
